### ISSUE TITLE
Weird issue if the number starts with a + and is at least 4 digits

### ISSUE THREAD

**Issue by Naereen** [o0morgan0o/CisterianNumbers#2]
Hi,
First of all, congrats and thanks for this nice project, it's fun and well done!

I tried to enter digits starting with a + or -, and the behavior is inconsistent: 1 and +1, 12 and +12, 123 and +123 generate the same symbols, but 1234 and +1234 don't!
See this small GIF:
![Peek 08-03-2021 19-33](https://user-images.githubusercontent.com/11994719/110365341-35e17980-8045-11eb-8e2e-15b15b226896.gif)

Thanks in advance!

**Comment by o0morgan0o** [comment]
Hi,
Because this little project wasn't aiming at allowing additions or mathematical operations, I am not surprised that these characters make the output irreguliar. The script parse the number of characters to have 1 cistercian symbol each 4 input characters.
So, on the last commit , it should be impossible now to enter something that is not a "pure" digit ("+" and ".").
I think, this remove any kind of confusion.

**Comment by Naereen** [comment]
Hi, thanks for your quick reply!
That's a great fix!! Well done!

**Comment by Naereen** [comment]
By the way I don't know if you care, but I discovered your project because it was quoted in the French video https://www.youtube.com/watch?v=vcm5d4Lr61E about this Cistercian numbering system, by a famous French historian vulgarizer.

Oh I just realized there is a typo in the name of the project, it's Cistercian and not Cisterian (c is missing), see <https://en.wikipedia.org/wiki/Cistercians>.

**Comment by o0morgan0o** [comment]
Oh really, didn't know that. Haha.
